from __future__ import annotations

import re

import psycopg

from services.db import connect


class PGCursor:
    def __init__(self, cursor):
        self._cursor = cursor
        self.lastrowid = None
        self._returned_row = None

    def execute(self, sql: str, params=None):
        if sql.strip().upper() == "BEGIN IMMEDIATE":
            sql = "BEGIN"

        sql = _convert_sql(sql)

        sql = re.sub(
            r"\bAUTOINCREMENT\b",
            "",
            sql,
            flags=re.IGNORECASE,
        )

        sql = re.sub(
            r"\bINTEGER\s+PRIMARY\s+KEY\s+\s*\b",
            "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ",
            sql,
            flags=re.IGNORECASE,
        )

        is_insert = bool(
            re.match(r"^\s*INSERT\s+INTO\b", sql, re.IGNORECASE)
        )

        if is_insert and not re.search(r"\bRETURNING\b", sql, re.IGNORECASE):
            sql = sql.rstrip().rstrip(";") + " RETURNING id"

        if params is None:
            self._cursor.execute(sql)
        else:
            self._cursor.execute(sql, tuple(params))

        if is_insert and self._cursor.description:
            self._returned_row = self._cursor.fetchone()

            if self._returned_row is not None:
                try:
                    self.lastrowid = int(self._returned_row["id"])
                except (KeyError, TypeError, ValueError):
                    self.lastrowid = None

        return self

    def executemany(self, sql: str, seq_of_params):
        sql = _convert_sql(sql)
        self._cursor.executemany(sql, seq_of_params)
        return self

    def fetchone(self):
        if self._returned_row is not None:
            row = self._returned_row
            self._returned_row = None
            return row

        return self._cursor.fetchone()

    def fetchall(self):
        rows = []

        if self._returned_row is not None:
            rows.append(self._returned_row)
            self._returned_row = None

        rows.extend(self._cursor.fetchall())
        return rows

    @property
    def rowcount(self):
        return self._cursor.rowcount

    @property
    def description(self):
        return self._cursor.description

    def close(self):
        self._cursor.close()

    def __iter__(self):
        if self._returned_row is not None:
            yield self._returned_row
            self._returned_row = None

        yield from self._cursor


class PGConnection:
    def __init__(self):
        self._conn = connect()

    def cursor(self):
        return PGCursor(self._conn.cursor())

    def execute(self, sql: str, params=None):
        cursor = self.cursor()
        cursor.execute(sql, params)
        return cursor

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()

    def executescript(self, sql: str):
        """
        Compatibility method for old SQLite initialization code.

        PostgreSQL already contains the migrated EasySurf schema.
        SQLite CREATE TABLE / INDEX / PRAGMA statements are skipped.
        """

        for statement in _split_script(sql):
            normalized = statement.strip().upper()

            if not normalized:
                continue

            if normalized.startswith("PRAGMA "):
                continue

            if normalized.startswith("CREATE TABLE"):
                continue

            if normalized.startswith("CREATE UNIQUE INDEX"):
                continue

            if normalized.startswith("CREATE INDEX"):
                continue

            self.execute(statement)

        return self


def _convert_sql(sql: str) -> str:
    """
    Convert common SQLite SQL syntax to PostgreSQL syntax.

    Question marks inside quoted SQL strings are preserved.
    """

    sql = re.sub(
        r"INTEGER\\s+PRIMARY\\s+KEY\\s+AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        sql,
        flags=re.IGNORECASE,
    )

    result = []
    in_single = False
    in_double = False
    i = 0

    while i < len(sql):
        char = sql[i]

        if char == "'" and not in_double:
            if in_single and i + 1 < len(sql) and sql[i + 1] == "'":
                result.append("''")
                i += 2
                continue

            in_single = not in_single
            result.append(char)
            i += 1
            continue

        if char == '"' and not in_single:
            in_double = not in_double
            result.append(char)
            i += 1
            continue

        if char == "?" and not in_single and not in_double:
            result.append("%s")
        else:
            result.append(char)

        i += 1

    return "".join(result)


def _split_script(sql: str) -> list[str]:
    return [
        statement.strip()
        for statement in sql.split(";")
        if statement.strip()
    ]


def db() -> PGConnection:
    return PGConnection()


def connect_db() -> PGConnection:
    return PGConnection()


def begin_immediate(conn: PGConnection) -> None:
    """
    PostgreSQL replacement for SQLite BEGIN IMMEDIATE.
    """

    conn.execute("BEGIN")


def is_integrity_error(exc: BaseException) -> bool:
    return isinstance(exc, psycopg.IntegrityError)


def is_database_error(exc: BaseException) -> bool:
    return isinstance(exc, psycopg.Error)


def get_lastrowid(
    cursor: PGCursor,
    table: str,
    id_column: str = "id",
) -> int | None:
    if cursor.lastrowid is not None:
        return int(cursor.lastrowid)

    return None
